package com.xm2013.admin.domain.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("sys_dept", "id", Dept.class);
		arp.addMapping("sys_dict", "id", Dict.class);
		arp.addMapping("sys_dict_group", "code", DictGroup.class);
		arp.addMapping("sys_document", "id", Document.class);
		arp.addMapping("sys_history", "id", History.class);
		arp.addMapping("sys_language", "id", Language.class);
		arp.addMapping("sys_language_resource", "id", LanguageResource.class);
		arp.addMapping("sys_language_resource_group", "name", LanguageResourceGroup.class);
		arp.addMapping("sys_menu", "id", Menu.class);
		arp.addMapping("sys_permission", "id", Permission.class);
		arp.addMapping("sys_role", "id", Role.class);
		arp.addMapping("sys_role_menu", "id", RoleMenu.class);
		arp.addMapping("sys_role_permission", "id", RolePermission.class);
		arp.addMapping("sys_user", "id", User.class);
		arp.addMapping("sys_user_data", "id", UserData.class);
		arp.addMapping("sys_user_role", "id", UserRole.class);
	}
}


