/*
 * MIT License
 *
 * Copyright (c) 2024 tuxming@sina.com / wechat: angft1
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

package com.xm2013.admin.domain.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("sys_dept", "id", Dept.class);
		arp.addMapping("sys_dict", "id", Dict.class);
		arp.addMapping("sys_dict_group", "code", DictGroup.class);
		arp.addMapping("sys_document", "id", Document.class);
		arp.addMapping("sys_history", "id", History.class);
		arp.addMapping("sys_language", "id", Language.class);
		arp.addMapping("sys_language_resource", "id", LanguageResource.class);
		arp.addMapping("sys_language_resource_group", "name", LanguageResourceGroup.class);
		arp.addMapping("sys_menu", "id", Menu.class);
		arp.addMapping("sys_permission", "id", Permission.class);
		arp.addMapping("sys_role", "id", Role.class);
		arp.addMapping("sys_role_menu", "id", RoleMenu.class);
		arp.addMapping("sys_role_permission", "id", RolePermission.class);
		arp.addMapping("sys_user", "id", User.class);
		arp.addMapping("sys_user_data", "id", UserData.class);
		arp.addMapping("sys_user_role", "id", UserRole.class);
	}
}


