package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dept extends BaseDept<Dept> {
	public static final Dept dao = new Dept().dao();
	
	/**
	 * 组织类型：0-个人，
	 */
	public static final int TYPE_SELF = 0;
	
	/**
	 * 组织类型：1-部门，
	 */
	public static final int TYPE_DEPARTMENT = 1;
	
	/**
	 * 组织类型：2-公司，
	 */
	public static final int TYPE_COMPANY = 2;
	
	/**
	 * 组织类型：3-集团，
	 */
	public static final int TYPE_GROUP = 3;
	
	
	
}

