package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseDept;
import com.xm2013.admin.validator.V;
import com.xm2013.admin.validator.Validate;
import com.xm2013.admin.validator.ValidateGroup;
import com.xm2013.admin.validator.ValidateType;

/**
 * Generated by JFinal.
 */
@V(value={
	@ValidateGroup(name="create", validates = {
		@Validate(field="parentId", type=ValidateType.NULLABLE, msg="上级节点不能为空"),
		@Validate(field="name", type=ValidateType.NOEMPTY, msg="组织名不能为空"),
	}),
})
@SuppressWarnings("serial")
public class Dept extends BaseDept<Dept> {
	public static final Dept dao = new Dept().dao();
	
	/**
	 * 组织类型：0-个人，
	 */
	public static final int TYPE_SELF = 0;
	
	/**
	 * 组织类型：1-部门，
	 */
	public static final int TYPE_DEPARTMENT = 1;
	
	/**
	 * 组织类型：2-公司，
	 */
	public static final int TYPE_COMPANY = 2;
	
	/**
	 * 组织类型：3-集团，
	 */
	public static final int TYPE_GROUP = 3;
	
	
	
}

