package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseDictGroup;
import com.xm2013.admin.validator.V;
import com.xm2013.admin.validator.Validate;
import com.xm2013.admin.validator.ValidateGroup;
import com.xm2013.admin.validator.ValidateType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@V(value={
	@ValidateGroup(name="create", validates = {
		@Validate(field="label", type=ValidateType.NOEMPTY, msg="显示名不能为空"),
		@Validate(field="code", type=ValidateType.CHAR_AND_NUMBER, msg="字典代码不合法"),
	}),
})
public class DictGroup extends BaseDictGroup<DictGroup> {
	public static final DictGroup dao = new DictGroup().dao();
	
	private String oldCode;

	public String getOldCode() {
		return oldCode;
	}

	public void setOldCode(String oldCode) {
		this.oldCode = oldCode;
	}
}

