package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseDict;
import com.xm2013.admin.validator.V;
import com.xm2013.admin.validator.Validate;
import com.xm2013.admin.validator.ValidateGroup;
import com.xm2013.admin.validator.ValidateType;
import com.xm2013.admin.validator.ValidateUnion;
import com.xm2013.admin.validator.ValidateUnions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@V(value={
	@ValidateGroup(name="create", validates = {
		@Validate(field="groupName", type=ValidateType.CHAR_AND_NUMBER, msg="字典名只能是数字字符"),
		@Validate(field="dictValue", type=ValidateType.NOEMPTY, msg="值不能为空"),
		@Validate(field="dictKey", type=ValidateType.NOEMPTY, msg="KEY不能为空"),
		@Validate(field="dictLabel", type=ValidateType.NOEMPTY, msg="显示名不能为空"),
		@Validate(field="type", type=ValidateType.NULLABLE, msg="类型不能为空")
	}),
	@ValidateGroup(name="update", validates = {
		@Validate(field="id", type=ValidateType.NULLABLE, msg="ID不能为空"),
	}),
})
@ValidateUnions(values={
	 @ValidateUnion(name="update", values= {"create", "update"}),
})
public class Dict extends BaseDict<Dict> {
	public static final Dict dao = new Dict().dao();
}

