package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseDocument;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Document extends BaseDocument<Document> {
	public static final Document dao = new Document().dao();
}

