package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class History extends BaseHistory<History> {
	public static final History dao = new History().dao();
}

