package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseLanguageResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LanguageResource extends BaseLanguageResource<LanguageResource> {
	public static final LanguageResource dao = new LanguageResource().dao();
}

