package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseLanguage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Language extends BaseLanguage<Language> {
	public static final Language dao = new Language().dao();
}

