package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseLanguageResourceGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LanguageResourceGroup extends BaseLanguageResourceGroup<LanguageResourceGroup> {
	public static final LanguageResourceGroup dao = new LanguageResourceGroup().dao();
}

