package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseLanguage;
import com.xm2013.admin.validator.V;
import com.xm2013.admin.validator.Validate;
import com.xm2013.admin.validator.ValidateGroup;
import com.xm2013.admin.validator.ValidateType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@V(value={
	@ValidateGroup(name="create", validates = {
		@Validate(field="label", type=ValidateType.NOEMPTY, msg="显示名不能为空"),
		@Validate(field="code", type=ValidateType.NOEMPTY, msg="语言代码不能为空"),
	}),
})
public class Language extends BaseLanguage<Language> {
	public static final Language dao = new Language().dao();
}

