package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseLanguageResource;
import com.xm2013.admin.validator.V;
import com.xm2013.admin.validator.Validate;
import com.xm2013.admin.validator.ValidateGroup;
import com.xm2013.admin.validator.ValidateType;

/**
 * Generated by JFinal.
 */
@V(value={
	@ValidateGroup(name="edit", validates = {
		@Validate(field="languageId", type=ValidateType.NULLABLE, msg="语言不能为空"),
		@Validate(field="category", type=ValidateType.NOEMPTY, msg="语言分组不能为空"),
		@Validate(field="resKey", type=ValidateType.NOEMPTY, msg="资源KEY不能为空"),
	}),
})
@SuppressWarnings("serial")
public class LanguageResource extends BaseLanguageResource<LanguageResource> {
	public static final LanguageResource dao = new LanguageResource().dao();
}

