package com.xm2013.admin.domain.model;

import java.util.ArrayList;
import java.util.List;

import com.xm2013.admin.domain.base.BaseMenu;
import com.xm2013.admin.validator.V;
import com.xm2013.admin.validator.Validate;
import com.xm2013.admin.validator.ValidateGroup;
import com.xm2013.admin.validator.ValidateType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@V(
	@ValidateGroup(name="create", validates = {
		@Validate(field="name", type=ValidateType.NOEMPTY, msg="菜单名不能为空"),
		@Validate(field="path", type=ValidateType.NOEMPTY, msg="URL不能为空"),
	})
)
public class Menu extends BaseMenu<Menu> {
	public static final Menu dao = new Menu().dao();
	
	public List<Menu> children = new ArrayList<Menu>();

	public List<Menu> getChildren() {
		return children;
	}

	public void setChildren(List<Menu> children) {
		this.children = children;
	}
	
}

