package com.xm2013.admin.domain.model;

import java.util.ArrayList;
import java.util.List;

import com.xm2013.admin.domain.base.BaseMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Menu extends BaseMenu<Menu> {
	public static final Menu dao = new Menu().dao();
	
	public List<Menu> children = new ArrayList<Menu>();

	public List<Menu> getChildren() {
		return children;
	}

	public void setChildren(List<Menu> children) {
		this.children = children;
	}
	
	
}

