package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BasePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permission extends BasePermission<Permission> {
	public static final Permission dao = new Permission().dao();
}

