package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BasePermission;
import com.xm2013.admin.validator.V;
import com.xm2013.admin.validator.Validate;
import com.xm2013.admin.validator.ValidateGroup;
import com.xm2013.admin.validator.ValidateType;

/**
 * Generated by JFinal.
 */
@V(value={
		@ValidateGroup(name="create", validates = {
			@Validate(field="groupName", type=ValidateType.NOEMPTY, msg="分组名不能为空"),
			@Validate(field="expression", type=ValidateType.NOEMPTY, msg="权限表达式不能为空"),
			@Validate(field="name", type=ValidateType.NOEMPTY, msg="权限名不能为空")
		}),
	})
@SuppressWarnings("serial")
public class Permission extends BasePermission<Permission> {
	public static final Permission dao = new Permission().dao();
}

