package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role().dao();
	
	/**
	 * 系统角色，最高角色，代码写死，不可设置
	 */
	public static final int TYPE_SYSTEM = 0;
	
	/**
	 * 高级管理员，可以手动分配
	 */
	public static final int TYPE_SUPER = 1;
	
	/**
	 * 普通管理员，可以手动分配
	 */
	public static final int TYPE_ADMIN = 2;
	
	/**
	 * 普通角色
	 */
	public static final int TYPE_NORMAL = 3; 
	
}

