package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseRole;
import com.xm2013.admin.validator.V;
import com.xm2013.admin.validator.Validate;
import com.xm2013.admin.validator.ValidateGroup;
import com.xm2013.admin.validator.ValidateType;

/**
 * Generated by JFinal.
 */
@V(value={
	@ValidateGroup(name="create", validates = {
		@Validate(field="roleName", type=ValidateType.NOEMPTY, msg="角色名不能为空"),
		@Validate(field="code", type=ValidateType.NOEMPTY, msg="角色代码不能为空"),
		@Validate(field="type", type=ValidateType.NULLABLE, msg="角色类型不一样")
	}),
})
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role().dao();
	
	/**
	 * 系统角色，最高角色，代码写死，不可设置
	 */
	public static final int TYPE_SYSTEM = 0;
	
	/**
	 * 高级管理员，可以手动分配
	 */
	public static final int TYPE_SUPER = 1;
	
	/**
	 * 普通管理员，可以手动分配
	 */
	public static final int TYPE_ADMIN = 2;
	
	/**
	 * 普通角色
	 */
	public static final int TYPE_NORMAL = 3; 
	
}

