package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleMenu extends BaseRoleMenu<RoleMenu> {
	public static final RoleMenu dao = new RoleMenu().dao();
}

