package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseUserData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserData extends BaseUserData<UserData> {
	public static final UserData dao = new UserData().dao();
}

