package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseUser;
import com.xm2013.admin.validator.V;
import com.xm2013.admin.validator.Validate;
import com.xm2013.admin.validator.ValidateGroup;
import com.xm2013.admin.validator.ValidateType;
import com.xm2013.admin.validator.ValidateUnion;
import com.xm2013.admin.validator.ValidateUnions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@V(value={
	@ValidateGroup(name="create", validates = {
		@Validate(field="username", type=ValidateType.CHAR_AND_NUMBER, msg="用户名只能是数字字符"),
		@Validate(field="fullname", type=ValidateType.NOEMPTY, msg="姓名不能为空"),
		@Validate(field="email", type=ValidateType.REG, value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}", msg="邮箱地址不合法"),
		@Validate(field="phone", type=ValidateType.REG, value="1[\\d]{10}", msg="电话号码不合法"),
		@Validate(field="deptId", type=ValidateType.NULLABLE, msg="组织不能为空"),
		@Validate(field="password", type=ValidateType.EQUALS, value="repassword", msg="两次密码输入不一致"),
	})
})
@ValidateUnions(values={
	 @ValidateUnion(name="update", values= {"create", "update"}),
})
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();
	public static final Integer STATUS_DELETE = 3;
}

