package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseUserData;
import com.xm2013.admin.validator.V;
import com.xm2013.admin.validator.Validate;
import com.xm2013.admin.validator.ValidateGroup;
import com.xm2013.admin.validator.ValidateType;

/**
 * Generated by JFinal.
 */
@V(value={
	@ValidateGroup(name="create", validates = {
		@Validate(field="userId", type=ValidateType.NULLABLE, msg="用户id不能为空"),
		@Validate(field="refId", type=ValidateType.NULLABLE, msg="组织ID/用户ID不能为空"),
		@Validate(field="type", type=ValidateType.NULLABLE, msg="类型不能为空"),
	}),
})
@SuppressWarnings("serial")
public class UserData extends BaseUserData<UserData> {
	public static final UserData dao = new UserData().dao();
}

