package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();
}

