/*
 * MIT License
 *
 * Copyright (c) 2024 tuxming@sina.com / wechat: angft1
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseUserData;
import com.xm2013.admin.validator.V;
import com.xm2013.admin.validator.Validate;
import com.xm2013.admin.validator.ValidateGroup;
import com.xm2013.admin.validator.ValidateType;

/**
 * Generated by JFinal.
 */
@V(value={
	@ValidateGroup(name="create", validates = {
		@Validate(field="userId", type=ValidateType.NULLABLE, msg="用户id不能为空"),
		@Validate(field="refId", type=ValidateType.NULLABLE, msg="组织ID/用户ID不能为空"),
		@Validate(field="type", type=ValidateType.NULLABLE, msg="类型不能为空"),
	}),
})
@SuppressWarnings("serial")
public class UserData extends BaseUserData<UserData> {
	public static final UserData dao = new UserData().dao();
	
	/**
	 * 具体的用户id
	 */
	public static int TYPE_USER = 1;
	
	/**
	 * 组织节点的id
	 */
	public static int TYPE_DEPT = 2;
	
	
}

