package com.xm2013.admin.domain.model;

import com.xm2013.admin.domain.base.BaseUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRole extends BaseUserRole<UserRole> {
	public static final UserRole dao = new UserRole().dao();
}

