export * from './home';
export * from './overview';
export * from './login';
export * from './sys/user';
export * from './sys//menu';
export * from './sys/role';
export * from './sys/permission'
export * from './sys/history'
export * from './sys/document'
export * from './sys/dept'
export * from './sys/lang'
export * from './sys/dict'