/*
 * MIT License
 *
 * Copyright (c) 2023 tuxming@sina.com / wechat: angft1
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 *//*
 * MIT License
 *
 * Copyright (c) 2023 tuxming@sina.com / wechat: angft1
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */package com.xm2013.admin.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.xm2013.admin.jfinal.generator.Col;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDocument<M extends BaseDocument<M>> extends Model<M> implements IBean {

	public static String COL_ID = "id";
	/**
	 * 文件名
	 */
	public static String COL_FILE_NAME = "file_name";
	/**
	 * 文件路径
	 */
	public static String COL_PATH = "path";
	/**
	 * 创建时间
	 */
	public static String COL_CREATED = "created";
	/**
	 * 创建人
	 */
	public static String COL_USER_ID = "user_id";
	/**
	 * 文件类型
	 */
	public static String COL_TYPE = "type";
	/**
	 * 文件说明
	 */
	public static String COL_REMARK = "remark";

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	@Col(tableName = "sys_document", tableLabel="文件信息", 
		fieldName = "id", colName = "id", 
		label = "")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 文件名
	 */
	public M setFileName(java.lang.String fileName) {
		set("file_name", fileName);
		return (M)this;
	}
	
	/**
	 * 文件名
	 */
	@Col(tableName = "sys_document", tableLabel="文件信息", 
		fieldName = "fileName", colName = "file_name", 
		label = "文件名")
	public java.lang.String getFileName() {
		return getStr("file_name");
	}

	/**
	 * 文件路径
	 */
	public M setPath(java.lang.String path) {
		set("path", path);
		return (M)this;
	}
	
	/**
	 * 文件路径
	 */
	@Col(tableName = "sys_document", tableLabel="文件信息", 
		fieldName = "path", colName = "path", 
		label = "文件路径")
	public java.lang.String getPath() {
		return getStr("path");
	}

	/**
	 * 创建时间
	 */
	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	@Col(tableName = "sys_document", tableLabel="文件信息", 
		fieldName = "created", colName = "created", 
		label = "创建时间")
	public java.util.Date getCreated() {
		return getDate("created");
	}

	/**
	 * 创建人
	 */
	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 创建人
	 */
	@Col(tableName = "sys_document", tableLabel="文件信息", 
		fieldName = "userId", colName = "user_id", 
		label = "创建人")
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 文件类型
	 */
	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 文件类型
	 */
	@Col(tableName = "sys_document", tableLabel="文件信息", 
		fieldName = "type", colName = "type", 
		label = "文件类型")
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 文件说明
	 */
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	/**
	 * 文件说明
	 */
	@Col(tableName = "sys_document", tableLabel="文件信息", 
		fieldName = "remark", colName = "remark", 
		label = "文件说明")
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}

