package com.xm2013.admin.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.xm2013.admin.jfinal.generator.Col;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserData<M extends BaseUserData<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	@Col(tableName = "sys_user_data", tableLabel="数据权限	", 
		fieldName = "id", colName = "id", 
		label = "")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 用户id
	 */
	@Col(tableName = "sys_user_data", tableLabel="数据权限	", 
		fieldName = "userId", colName = "user_id", 
		label = "用户id")
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 拥有的组织节点
	 */
	public M setDeptPath(java.lang.String deptPath) {
		set("dept_path", deptPath);
		return (M)this;
	}
	
	/**
	 * 拥有的组织节点
	 */
	@Col(tableName = "sys_user_data", tableLabel="数据权限	", 
		fieldName = "deptPath", colName = "dept_path", 
		label = "拥有的组织节点")
	public java.lang.String getDeptPath() {
		return getStr("dept_path");
	}

}

