package com.xm2013.admin.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.xm2013.admin.jfinal.generator.Col;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLanguage<M extends BaseLanguage<M>> extends Model<M> implements IBean {

	public static String COL_ID = "id";
	public static String COL_LABEL = "label";
	public static String COL_CODE = "code";

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	@Col(tableName = "sys_language", tableLabel="国际化支持的语言列表", 
		fieldName = "id", colName = "id", 
		label = "")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 显示名
	 */
	public M setLabel(java.lang.String label) {
		set("label", label);
		return (M)this;
	}
	
	/**
	 * 显示名
	 */
	@Col(tableName = "sys_language", tableLabel="国际化支持的语言列表", 
		fieldName = "label", colName = "label", 
		label = "显示名")
	public java.lang.String getLabel() {
		return getStr("label");
	}

	/**
	 * 语言代码
	 */
	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}
	
	/**
	 * 语言代码
	 */
	@Col(tableName = "sys_language", tableLabel="国际化支持的语言列表", 
		fieldName = "code", colName = "code", 
		label = "语言代码")
	public java.lang.String getCode() {
		return getStr("code");
	}

}

