package com.xm2013.admin.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.xm2013.admin.jfinal.generator.Col;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePermission<M extends BasePermission<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	@Col(tableName = "sys_permission", tableLabel="权限表", 
		fieldName = "id", colName = "id", 
		label = "")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 分组名：防止权限多了不容易区分，使用分组容易区分
	 */
	public M setGroupName(java.lang.String groupName) {
		set("group_name", groupName);
		return (M)this;
	}
	
	/**
	 * 分组名：防止权限多了不容易区分，使用分组容易区分
	 */
	@Col(tableName = "sys_permission", tableLabel="权限表", 
		fieldName = "groupName", colName = "group_name", 
		label = "分组名：防止权限多了不容易区分，使用分组容易区分")
	public java.lang.String getGroupName() {
		return getStr("group_name");
	}

	/**
	 * 权限名
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 权限名
	 */
	@Col(tableName = "sys_permission", tableLabel="权限表", 
		fieldName = "name", colName = "name", 
		label = "权限名")
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 权限表达式
	 */
	public M setExpression(java.lang.String expression) {
		set("expression", expression);
		return (M)this;
	}
	
	/**
	 * 权限表达式
	 */
	@Col(tableName = "sys_permission", tableLabel="权限表", 
		fieldName = "expression", colName = "expression", 
		label = "权限表达式")
	public java.lang.String getExpression() {
		return getStr("expression");
	}

}

