package com.xm2013.admin.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.xm2013.admin.jfinal.generator.Col;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserRole<M extends BaseUserRole<M>> extends Model<M> implements IBean {

	public static String COL_ID = "id";
	/**
	 * 角色id
	 */
	public static String COL_ROLE_ID = "role_id";
	/**
	 * 用户id
	 */
	public static String COL_USER_ID = "user_id";

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	@Col(tableName = "sys_user_role", tableLabel="用户角色表", 
		fieldName = "id", colName = "id", 
		label = "")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 角色id
	 */
	public M setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
		return (M)this;
	}
	
	/**
	 * 角色id
	 */
	@Col(tableName = "sys_user_role", tableLabel="用户角色表", 
		fieldName = "roleId", colName = "role_id", 
		label = "角色id")
	public java.lang.Integer getRoleId() {
		return getInt("role_id");
	}

	/**
	 * 用户id
	 */
	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 用户id
	 */
	@Col(tableName = "sys_user_role", tableLabel="用户角色表", 
		fieldName = "userId", colName = "user_id", 
		label = "用户id")
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

}

