package com.xm2013.admin.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.xm2013.admin.jfinal.generator.Col;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLanguageResourceGroup<M extends BaseLanguageResourceGroup<M>> extends Model<M> implements IBean {

	public static String COL_NAME = "name";

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	@Col(tableName = "sys_language_resource_group", tableLabel="", 
		fieldName = "name", colName = "name", 
		label = "")
	public java.lang.String getName() {
		return getStr("name");
	}

}

