/*
 * MIT License
 *
 * Copyright (c) 2023 tuxming@sina.com / wechat: angft1
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 *//*
 * MIT License
 *
 * Copyright (c) 2023 tuxming@sina.com / wechat: angft1
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */package com.xm2013.admin.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.xm2013.admin.jfinal.generator.Col;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRole<M extends BaseRole<M>> extends Model<M> implements IBean {

	public static String COL_ID = "id";
	/**
	 * 角色名
	 */
	public static String COL_ROLE_NAME = "role_name";
	/**
	 * 角色标识，代码一般用它作为判断
	 */
	public static String COL_CODE = "code";
	/**
	 * 角色类型： 用它来判断角色级别的高低：0-sys, 1-super，2-admin普通管理员，3-普通角色，一般建议使用普通角色
	 */
	public static String COL_TYPE = "type";
	/**
	 * 创建人
	 */
	public static String COL_CREATER = "creater";

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	@Col(tableName = "sys_role", tableLabel="角色表", 
		fieldName = "id", colName = "id", 
		label = "")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 角色名
	 */
	public M setRoleName(java.lang.String roleName) {
		set("role_name", roleName);
		return (M)this;
	}
	
	/**
	 * 角色名
	 */
	@Col(tableName = "sys_role", tableLabel="角色表", 
		fieldName = "roleName", colName = "role_name", 
		label = "角色名")
	public java.lang.String getRoleName() {
		return getStr("role_name");
	}

	/**
	 * 角色标识，代码一般用它作为判断
	 */
	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}
	
	/**
	 * 角色标识，代码一般用它作为判断
	 */
	@Col(tableName = "sys_role", tableLabel="角色表", 
		fieldName = "code", colName = "code", 
		label = "角色标识，代码一般用它作为判断")
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 角色类型： 用它来判断角色级别的高低：0-sys, 1-super，2-admin普通管理员，3-普通角色，一般建议使用普通角色
	 */
	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 角色类型： 用它来判断角色级别的高低：0-sys, 1-super，2-admin普通管理员，3-普通角色，一般建议使用普通角色
	 */
	@Col(tableName = "sys_role", tableLabel="角色表", 
		fieldName = "type", colName = "type", 
		label = "角色类型： 用它来判断角色级别的高低：0-sys, 1-super，2-admin普通管理员，3-普通角色，一般建议使用普通角色")
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 创建人
	 */
	public M setCreater(java.lang.Integer creater) {
		set("creater", creater);
		return (M)this;
	}
	
	/**
	 * 创建人
	 */
	@Col(tableName = "sys_role", tableLabel="角色表", 
		fieldName = "creater", colName = "creater", 
		label = "创建人")
	public java.lang.Integer getCreater() {
		return getInt("creater");
	}

}

