package com.xm2013.admin.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.xm2013.admin.jfinal.generator.Col;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseHistory<M extends BaseHistory<M>> extends Model<M> implements IBean {

	public static String COL_ID = "id";
	public static String COL_USER_ID = "user_id";
	public static String COL_USERNAME = "username";
	public static String COL_IP_ADDR = "ip_addr";
	public static String COL_TYPE = "type";
	public static String COL_CREATED = "created";
	public static String COL_REMARK = "remark";
	public static String COL_SEQ = "seq";
	public static String COL_HISTORY_ID = "history_id";

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	@Col(tableName = "sys_history", tableLabel="日志表", 
		fieldName = "id", colName = "id", 
		label = "")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 操作人
	 */
	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 操作人
	 */
	@Col(tableName = "sys_history", tableLabel="日志表", 
		fieldName = "userId", colName = "user_id", 
		label = "操作人")
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 操作人名
	 */
	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	/**
	 * 操作人名
	 */
	@Col(tableName = "sys_history", tableLabel="日志表", 
		fieldName = "username", colName = "username", 
		label = "操作人名")
	public java.lang.String getUsername() {
		return getStr("username");
	}

	/**
	 * ip地址
	 */
	public M setIpAddr(java.lang.String ipAddr) {
		set("ip_addr", ipAddr);
		return (M)this;
	}
	
	/**
	 * ip地址
	 */
	@Col(tableName = "sys_history", tableLabel="日志表", 
		fieldName = "ipAddr", colName = "ip_addr", 
		label = "ip地址")
	public java.lang.String getIpAddr() {
		return getStr("ip_addr");
	}

	/**
	 * 操作类型
	 */
	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 操作类型
	 */
	@Col(tableName = "sys_history", tableLabel="日志表", 
		fieldName = "type", colName = "type", 
		label = "操作类型")
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 操作时间
	 */
	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	/**
	 * 操作时间
	 */
	@Col(tableName = "sys_history", tableLabel="日志表", 
		fieldName = "created", colName = "created", 
		label = "操作时间")
	public java.util.Date getCreated() {
		return getDate("created");
	}

	/**
	 * 请求参数
	 */
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	/**
	 * 请求参数
	 */
	@Col(tableName = "sys_history", tableLabel="日志表", 
		fieldName = "remark", colName = "remark", 
		label = "请求参数")
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 序号，当一个请求的参数过长时，会分成多段存储起来
	 */
	public M setSeq(java.lang.Integer seq) {
		set("seq", seq);
		return (M)this;
	}
	
	/**
	 * 序号，当一个请求的参数过长时，会分成多段存储起来
	 */
	@Col(tableName = "sys_history", tableLabel="日志表", 
		fieldName = "seq", colName = "seq", 
		label = "序号，当一个请求的参数过长时，会分成多段存储起来")
	public java.lang.Integer getSeq() {
		return getInt("seq");
	}

	/**
	 * id: 当一个请求过长是，这个多个存储使用这一个id
	 */
	public M setHistoryId(java.lang.String historyId) {
		set("history_id", historyId);
		return (M)this;
	}
	
	/**
	 * id: 当一个请求过长是，这个多个存储使用这一个id
	 */
	@Col(tableName = "sys_history", tableLabel="日志表", 
		fieldName = "historyId", colName = "history_id", 
		label = "id: 当一个请求过长是，这个多个存储使用这一个id")
	public java.lang.String getHistoryId() {
		return getStr("history_id");
	}

}

