package com.xm2013.admin.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.xm2013.admin.jfinal.generator.Col;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRoleMenu<M extends BaseRoleMenu<M>> extends Model<M> implements IBean {

	public static String COL_ID = "id";
	public static String COL_MENU_ID = "menu_id";
	public static String COL_ROLE_ID = "role_id";

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	@Col(tableName = "sys_role_menu", tableLabel="角色菜单表", 
		fieldName = "id", colName = "id", 
		label = "")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setMenuId(java.lang.Integer menuId) {
		set("menu_id", menuId);
		return (M)this;
	}
	
	@Col(tableName = "sys_role_menu", tableLabel="角色菜单表", 
		fieldName = "menuId", colName = "menu_id", 
		label = "")
	public java.lang.Integer getMenuId() {
		return getInt("menu_id");
	}

	public M setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
		return (M)this;
	}
	
	@Col(tableName = "sys_role_menu", tableLabel="角色菜单表", 
		fieldName = "roleId", colName = "role_id", 
		label = "")
	public java.lang.Integer getRoleId() {
		return getInt("role_id");
	}

}

