/*
 * MIT License
 *
 * Copyright (c) 2023 tuxming@sina.com / wechat: angft1
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 *//*
 * MIT License
 *
 * Copyright (c) 2023 tuxming@sina.com / wechat: angft1
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */package com.xm2013.admin.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.xm2013.admin.jfinal.generator.Col;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public static String COL_ID = "id";
	/**
	 * 上级节点id, 顶级为0
	 */
	public static String COL_PARENT_ID = "parent_id";
	/**
	 * 菜单名
	 */
	public static String COL_NAME = "name";
	/**
	 * 显示顺序，从小到大排序
	 */
	public static String COL_SORT = "sort";
	/**
	 * 菜单跳转链接
	 */
	public static String COL_PATH = "path";
	/**
	 * 附加参数
	 */
	public static String COL_QUERY = "query";
	/**
	 * 类型：0-目录，1-菜单
	 */
	public static String COL_TYPE = "type";
	/**
	 * 状态：0-正常，1-禁用
	 */
	public static String COL_STATUS = "status";
	/**
	 * 菜单图标
	 */
	public static String COL_ICON = "icon";

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	@Col(tableName = "sys_menu", tableLabel="菜单权限表", 
		fieldName = "id", colName = "id", 
		label = "")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 上级节点id, 顶级为0
	 */
	public M setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
		return (M)this;
	}
	
	/**
	 * 上级节点id, 顶级为0
	 */
	@Col(tableName = "sys_menu", tableLabel="菜单权限表", 
		fieldName = "parentId", colName = "parent_id", 
		label = "上级节点id, 顶级为0")
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	/**
	 * 菜单名
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 菜单名
	 */
	@Col(tableName = "sys_menu", tableLabel="菜单权限表", 
		fieldName = "name", colName = "name", 
		label = "菜单名")
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 显示顺序，从小到大排序
	 */
	public M setSort(java.lang.Integer sort) {
		set("sort", sort);
		return (M)this;
	}
	
	/**
	 * 显示顺序，从小到大排序
	 */
	@Col(tableName = "sys_menu", tableLabel="菜单权限表", 
		fieldName = "sort", colName = "sort", 
		label = "显示顺序，从小到大排序")
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	/**
	 * 菜单跳转链接
	 */
	public M setPath(java.lang.String path) {
		set("path", path);
		return (M)this;
	}
	
	/**
	 * 菜单跳转链接
	 */
	@Col(tableName = "sys_menu", tableLabel="菜单权限表", 
		fieldName = "path", colName = "path", 
		label = "菜单跳转链接")
	public java.lang.String getPath() {
		return getStr("path");
	}

	/**
	 * 附加参数
	 */
	public M setQuery(java.lang.String query) {
		set("query", query);
		return (M)this;
	}
	
	/**
	 * 附加参数
	 */
	@Col(tableName = "sys_menu", tableLabel="菜单权限表", 
		fieldName = "query", colName = "query", 
		label = "附加参数")
	public java.lang.String getQuery() {
		return getStr("query");
	}

	/**
	 * 类型：0-目录，1-菜单
	 */
	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 类型：0-目录，1-菜单
	 */
	@Col(tableName = "sys_menu", tableLabel="菜单权限表", 
		fieldName = "type", colName = "type", 
		label = "类型：0-目录，1-菜单")
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 状态：0-正常，1-禁用
	 */
	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	/**
	 * 状态：0-正常，1-禁用
	 */
	@Col(tableName = "sys_menu", tableLabel="菜单权限表", 
		fieldName = "status", colName = "status", 
		label = "状态：0-正常，1-禁用")
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 菜单图标
	 */
	public M setIcon(java.lang.String icon) {
		set("icon", icon);
		return (M)this;
	}
	
	/**
	 * 菜单图标
	 */
	@Col(tableName = "sys_menu", tableLabel="菜单权限表", 
		fieldName = "icon", colName = "icon", 
		label = "菜单图标")
	public java.lang.String getIcon() {
		return getStr("icon");
	}

}

